### ISSUE TITLE
Last table cell isn't displayed if it doesn't have any data

### ISSUE THREAD

**Issue by izuzak** [atom/markdown-preview#206]
_From @fmsedrez on February 24, 2015 19:48_
# Markdown Preview display error

Markdown Preview windows does not display the last cell on last line if it is empty. 
View line **Show Available Snippets** in print screen.
- Ubuntu 14.10
- Atom 0.182.0
- [Markdown file](https://github.com/fmsedrez/atom-keyboard-shortcuts/blob/master/README.md)

| Atom: Code View and Markdown Preview | GitHub Site View |
| :-: | :-: |
| ![screenshot from 2015-02-24 16 19 22](https://cloud.githubusercontent.com/assets/1216898/6357330/6740c2ec-bc42-11e4-8aa8-dd4c04bd344a.png) | ![screenshot from 2015-02-24 16 31 29](https://cloud.githubusercontent.com/assets/1216898/6357352/9cbc10de-bc42-11e4-9560-9b5b952da256.png) |

_Copied from original issue: atom/atom#5719_

**Comment by izuzak** [comment]
@fmsedrez This seems to be a bug in Marked, the markdown parsing library which this package uses:

https://github.com/chjj/marked/pull/357

**Comment by MaXwellFalstein** [comment]
I believe this is still a bug in Marked, so there is no fix as of now. I hope there will be a fix soon; it is only a little annoying.

**Comment by myidealab** [comment]
As a workaround, I put a period in the last cell. It is not very visible.

**Comment by MaXwellFalstein** [comment]
One workaround is to put a period in the last cell with the colour matching the cell colour.

**Comment by MaXwellFalstein** [comment]
I have done some digging around what is causing this issue.

First reported: tessel/t2-docs#113
Workaround found (&nbsp;): tessel/t2-docs#128
Not fixed in marked: [chjj/marked#357

atom/markdown-preview will not be able to fix this until chjj/marked/357 is merged or something else fixes it.

**Comment by GraemeHawker** [comment]
issue is reported as fixed in markedjs, but still exists in atom https://github.com/markedjs/marked/pull/697

**Comment by rafeca** [comment]
This issue can be resolved by upgrading the version of `markedjs` that this package is using. The main issue is that `mardown-preview` is using a package called [`roaster`](https://github.com/gjtorikian/roaster) so we would need to upgrade that package first.

Since `roaster` is unmaintained (and even its creator [mentioned that it was a hacked-together lib](https://github.com/gjtorikian/roaster/pull/20#issuecomment-239033234) on the last PR that was merged 2 years ago), I'm going to explore ditching `roaster` in favor of using `markedjs` directly.

There's some functionality that we'll need to port from `roaster` to `markdown-preview` though:

1. Handle the `yaml` frontmatter tags ([source](https://github.com/gjtorikian/roaster/blob/master/src/convert_frontmatter.coffee)). We can use the [`yaml-front-matter`](https://www.npmjs.com/package/yaml-front-matter) package to help us with this.
2. Convert github emoji tags (e.g `:rocket:`) to the actual emojis.
