### ISSUE TITLE
Markdown Syntax Highlighting not making a text bold if it's a part of a link

### ISSUE THREAD

**Issue by 50Wliu** [atom/markdown-preview#218]
_From @diagramatics on March 18, 2015 10:37_

I'm talking about `[**this**]()`. Markdown Preview seems to make it a valid formatting but the editor doesn't make it bold, only color highlights.

To prove it, [**this is a valid formatting**](#) in GitHub.

_Copied from original issue: atom/atom#6017_

**Comment by diagramatics** [comment]
Wait, this is for the preview, right? The problem here is on the text editor, not on the preview. The preview works fine, it's just that on the editor it isn't highlighting the text as well as making it bold.
![](https://cloud.githubusercontent.com/assets/5153378/6708859/36ea8a32-cdc8-11e4-9d66-d6d6d1b6b694.png)

**Comment by 50Wliu** [comment]
Ah, I thought when you mentioned Markdown Preview you were saying that was what was rendering incorrectly.  I guess I'll move it again :P.

**Comment by 50Wliu** [comment]
This issue was moved to atom/language-gfm#82

**Comment by diagramatics** [comment]
Ah, I've been trying to find the right repo to post the issue to. Thanks!
