### ISSUE TITLE
Style info gets lost on save to HTML

### ISSUE THREAD

**Issue by Liamsi** [atom/markdown-preview#221]
First of all: Thanks for this great addon.

If I try saving the preview of a very simple example containing some js code to HTML, the CSS-style information of the syntax hightlighting is lost. Does this happen on purpose? I hacked a little on the markdown-pdf addon (https://github.com/travs/markdown-pdf) to save an HTML file with all the syntax highlighting. I could provide you with a patch if have some spare time on the weekend. 
I use atom version 0.187.0 and mardown-preview version v0.144.0 and the atom dark theme on arch linux. 

Here is some examplary markdown to reproduce the problem (and the output HTML).
 
--------------------------------------------------------------------------------------------------------

simple sample markdown file
---------------
test :+1: 
```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
--------------------------------------------------------------------------------------------------------

Furthermore, references to the emojis and such are not exported correctly in windows (directory seperators "/" and "\" get mixed up). As I do not use windows a lot and I am to lazy to open another issue, I do not really care about that.

![html_output](https://cloud.githubusercontent.com/assets/7441766/6809791/f157c540-d25c-11e4-8d70-7384e8e4690f.png)

**Comment by lee-dohm** [comment]
I extracted the sample Markdown in case it helps others with investigations:

    simple sample markdown file
    ---------------
    test :+1: 
    ```javascript
    var s = "JavaScript syntax highlighting";
    alert(s);
    ```

Here is a screenshot of what I see after I save as HTML and open in Chrome from Atom v0.188.0-19975ce on Mac OS X 10.10.2:

![black-on-dark-gray](https://cloud.githubusercontent.com/assets/1038121/6810874/2abdd838-d221-11e4-805d-2262a114a93d.png)

It appears what is going on is that the Save as HTML exports what it can of your syntax theme so that the colorization of the code block is the same as it is in your editor view. But if a portion of the code is the default scope (I believe in this case `.source.js`) then the text color defaults to black:

```html
<span class="storage modifier js">
  <span>var</span>
</span>
<span>&nbsp;s&nbsp;</span>
<span class="keyword operator js">
  <span>=</span>
</span>
```

which in dark themes is not a great selection :grinning:

**Comment by Liamsi** [comment]
I wanted to fix this myself but I found (using v0.145.0 and atom 0.188.0):
![save_as_html](https://cloud.githubusercontent.com/assets/7441766/6886548/481a94ec-d641-11e4-9113-e7a1d8bd77e3.png)
Although the colors are not exactly the same I get a readable html file. I think its ok to close this issue. 
From the atom changelog: "Saving HTML from markdown now correctly includes current text editor styling for code blocks." 
https://github.com/atom/atom/releases/tag/v0.188.0

**Comment by Liamsi** [comment]
@lee-dohm and thank you for your time and help

**Comment by lee-dohm** [comment]
You're welcome, I'm glad I could help! :grinning:
