### ISSUE TITLE
Add support for CriticMarkup?

### ISSUE THREAD

**Issue by claman** [atom/markdown-preview#299]
[CriticMarkup](https://github.com/CriticMarkup/CriticMarkup-toolkit) and Markdown seem to go together pretty well. Would it be possible to add support for CriticMarkup to the previewer?

**Comment by thomasjo** [comment]
Since CriticMarkup is not a flavor of Markdown, this should be implemented as a separate package. This is the same reasoning behind [not adding CrititMarkup support](https://github.com/atom/language-gfm/issues/73) to language-gfm.

Perhaps this would be a good time for a community effort around a generic preview package concept ala autocomplete-plus, linter, etc. Essentially a service-backed preview infrastructure.

**Comment by lee-dohm** [comment]
I opened an enhancement suggestion for a viewer infrastructure that covers what I believe @thomasjo is suggesting https://github.com/atom/atom/issues/6817
