### ISSUE TITLE
External API

### ISSUE THREAD

**Issue by ITler** [atom/markdown-preview#312]
I would like to use the capabilities of this plugin from outside atom (e.g. shell command), like

    markdown-preview-api -in file.md -type html -out file.md.html

The outputted file should respect the plugin settings, so that it looks same like preview in atom. Is this possible?

**Comment by thomasjo** [comment]
This will never be directly supported by this package, since it just that, a package.

You might be able to make a minimal executable wrapper that spins up an Atom background process, interacts with this package and yanks resulting markup. Not impossible, but likely not worth the effort.
You'll better off simply using an existing markdown solution meant to be executed as a command line tool, or use [marked](https://github.com/chjj/marked) (which is what this package uses) and mimic what we do here.
