### ISSUE TITLE
can not preview photo ?

### ISSUE THREAD

**Issue by litaotao** [atom/markdown-preview#323]
when use `ctrl + shift + m` to preview markdown in atom, it seems that the picture cannot be rendered. 

<img width="838" alt="screen_shot 2015-10-30 at 1 43 51 pm" src="https://cloud.githubusercontent.com/assets/4660350/10839237/5127f0ce-7f0c-11e5-91b1-61a9922537f8.png">

**Comment by izuzak** [comment]
Thanks for the report. I think you're seeing this issue: https://github.com/atom/markdown-preview/issues/146 because you're using relative links. Check that out. If I'm wrong, please provide more details about your problem and explain in what way it's different (also provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)).
