### ISSUE TITLE
API Blueprint support

### ISSUE THREAD

**Issue by samekmichal** [atom/markdown-preview#350]
It would be great, if one could render a preview for [API Blueprint](https://apiblueprint.org/) files ``*.apib`` - since it is written using *markdown*.
Special handling might be only needed for the API Blueprint *header*
```
FORMAT: 1A
HOST: http://myapi.org/api
```

**Comment by mnquintana** [comment]
Thanks for the suggestion! Looking through the language docs however, it's pretty clear that this is only based on Markdown, rather than fully CommonMark or GFM-compliant. This would make for a great package, however – someone could easily fork markdown-preview to support API Blueprint, much like was done for [asciidoc](https://github.com/asciidoctor/atom-asciidoc-preview).
