### ISSUE TITLE
Add an option to ignore YAML front-matter data when previewing

### ISSUE THREAD

**Issue by fmaida** [atom/markdown-preview#361]
Hello. If I can suggest a feature I'd really like to see implemented in the Markdown preview, since some of my markdown files are blog posts that also contains an initial YAML front-matter formatted text, I'd really like to see an option to ignore the YAML front-matter inital part when previewing the file.

For example, if I have a blog post written in markdown like this one:

``` md

---
title: my first post
date: 2016-01-18
tags: stuff, other stuff

---

# My first post

Hello world, this is my first post.
```

If I preview this code right now I can see that the front-matter part is converted into a table, but personally speaking I'd like to be able to preview it with Atom without showing it. So I'm thinking about an option that -when enabled- could tell the preview system to strip away the first five lines, and then the result should look something like this:

``` html
<h1>My first post</h1>

Hello world, this is my first post.
```

If this request also makes sense for you, please consider to add this feature in one of your next updates.

Thanks for having read my message and best regards

**Comment by mnquintana** [comment]
Refs https://github.com/atom/markdown-preview/issues/26

**Comment by chemzqm** [comment]
:+1: for this, the only thing I use Atom for is to write my blog post

**Comment by gligoran** [comment]
+1

**Comment by lee-dohm** [comment]
Since the last time we updated this, we've reconsidered and don't really want to maintain the separate code paths that would be required by such an option. It isn't particularly obtrusive and the markdown-preview package isn't intended to give a 100% faithful rendering of the source Markdown as HTML. If a fully faithful rendering is needed, using a system such as Jekyll or a Markdown converter and a web browser would be the best solution.

Thanks for the feedback.
