### ISSUE TITLE
When the preview page  refreshed,it won't scroll to the correct place.thanks~

### ISSUE THREAD

**Issue by yalishizhude** [atom/markdown-preview#370]

**Comment by jordwalke** [comment]
I noticed this too. Is it a recent bug?

**Comment by chatziko** [comment]
+1
greatly reduces the usefulness of this (otherwise awesome :D) package

**Comment by lee-dohm** [comment]
Can someone provide some repro steps for this? I'm unsure exactly what "the correct place" means in this context.

**Comment by chatziko** [comment]
After a bit of testing, turns out that the problem is not as bad as I initially thought.

 * create a "long" markdown document such that the content does not fit in the preview pane and needs to scroll.
 * Scroll the preview pane somewhere in the middle
 * make a change, the preview updates without moving
 * now scroll to the very bottom of the preview pane
 * make a change, now when it updates the preview automatically scrolls up so you can no longer see the bottom, you need to scroll again.

It seems that it only happens near the very bottom (still a bit annoying, cause it's common to add text at the bottom).
Tested with atom 1.5.4 on ubuntu 15.10, markdown-preview 0.157.1

**Comment by jordwalke** [comment]
It's annoying because you often *are* writing at the bottom of a markdown document, so there's an increased likelihood of hitting this issue.

**Comment by eggboxio** [comment]
Getting this on OSX too. I think @chatziko has summed this up well, can the more-information-needed tag be removed?

**Comment by dbpolito** [comment]
I would love to see this fixed too =)

**Comment by Nejik** [comment]
such problem in windows 8, Atom 1.7.3. Package version v0.158.0

**Comment by massenz** [comment]
This is actually __not__ a _minor_ issue: it pretty much renders the preview unusable: you are typically editing at the bottom of your `.md` file and would like to see the changes as you type.

However, after the preview does a __full__ refresh (BTW, why? I may have just typed a few words at the very end of the doc...) the preview scrolls all the way back to the top, so I need to "context switch", go to the preview pane and scroll back down - only to be back to square one a few seconds after... hugely annoying.

This __by far__ the __BEST__ markdown editor with preview I've used; please please fix this issue, as I'd love to continue using it!

**Comment by nitrocode** [comment]
+1 I have the same issue

**Comment by TimothyBramlett** [comment]
+1 also.  Have the same issue and it does make it almost unusable.

**Comment by knowname** [comment]
I tried several things and figured out, that the problem especially occurs if a codeblock is within the file. The attachment contains such a markdown file.

To reproduce:

1. Download, unzip and open file with atom or create a markdown document longer than one screensize including a codeblock
1. Press Ctrl+Shift+m to open the Markdown preview
1. Scroll to the end of the Markdown preview
1. Scroll to the end of the editor
1. Type something => Markdown previews cursor jumps up and loses correct position.

My suspicion is that the length of the markdown preview is calculated wrong, because a codeblock behaves differently (long code get a scrollbar).

[loremipsum.md.zip](https://github.com/atom/markdown-preview/files/500287/loremipsum.md.zip)

**Comment by JunoJunho** [comment]
Have same issue +1

**Comment by divyenduz** [comment]
Hey, is anyone working on solving this one ? I see a duplicate closed long back ? https://github.com/atom/markdown-preview/issues/24

I can collaborate with anyone working on this one or start a fresh PR to solve it.

Need help from maintainers to see if someone is thinking about this one. 

Thanks

**Comment by 50Wliu** [comment]
I don't believe anyone is actively working on this issue at the moment.  Feel free to take it on.

**Comment by marcodiiga** [comment]
I decided to write a lengthy markdown document and this was somewhat bothering me so I hacked into atom to make it scroll to the rendered location:

* Augmented the markdown parser with original line data embedding https://github.com/marcodiiga/marked/commit/573bc958e2418d5b993c687164065ba4271da31e
* Modified the markdown preview view to quickly scroll to the right rendered element https://github.com/marcodiiga/markdown-preview/commit/1ab44de5c6166cf78af55a6144f6ed16706fe157

This code is a quick hack though, it needs refactoring and probably some more testing. It seems to work anyway and it allows me to quickly see the result without having to find the scroll place all the way down each time.

**Comment by divyenduz** [comment]
@50Wliu : The PR is ready for further discussion. Thanks.

**Comment by glw** [comment]
I am still experiencing the wrong scrolling behavior. I see this is closed though.

Im using Ubuntu 
markdown-preview 0.159.6
atom 1.15.0

**Comment by rsese** [comment]
> atom 1.15.0

The current stable release version of Atom is 1.28.1 - can you install the latest version of Atom using one the [documented installation methods](https://flight-manual.atom.io/getting-started/sections/installing-atom/) and if you can still reproduce, please open a new issue and fill out the issue template and we'll take a look.

**Comment by glw** [comment]
ok, thank you. I will update.
