### ISSUE TITLE
Inserting images more easily

### ISSUE THREAD

**Issue by pabloab** [atom/markdown-preview#418]
Something similar as Ghost [handles images](http://docs.ghost.org/usage/writing/) (scroll to bottom):

Have the ability to insert an image by first entering ![]() into the editor. This should a window to select the image.

**Comment by lee-dohm** [comment]
The markdown-preview doesn't change the behavior of the editor, so your suggestion wouldn't be applicable to this package. Additionally, this isn't something that the Atom team is going to have the resources for but it sounds like a great idea for a community package. I'll mark this as a `package-idea` so that community members that want to try to build cool things can give it a try!

Thanks for the suggestion!
