### ISSUE TITLE
Is it possible to automatically copy the preview HTML formatted output?

### ISSUE THREAD

**Issue by angelr91** [atom/markdown-preview#455]
Hi,

I use markdown for quick pretty notes and want to use autohotkey to automatically start an atom markdown note and another key to automatically copy the output to paste to an email or one note. Anyone know if this is already possible?

Miguel

**Comment by thomasjo** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
