### ISSUE TITLE
Markdown preview causes screen to blur until restart

### ISSUE THREAD

**Issue by libeclipse** [atom/markdown-preview#470]
### Description

When pressing `Ctrl+Shift+M`, the markdown preview pane appears but the whole screen is blurred as if a transition failed to disappear. I will attach a screenshot. This does not happen in safe-mode.

### Steps to Reproduce

1. Open a markdown file.
2. Press Ctrl + Shift + M.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time. 100%

### Versions

```
~                                                                                                        
▶ atom --version
Atom    : 1.14.4
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0

~                                                                                                        
▶ apm --version
(node:2265) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.16.1
npm  4.4.1
node 7.7.2 x64
python 2.7.13
git 2.12.0

~                                                                                                        
▶ uname -a
Linux ArchSystem 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
```

![screenshot from 2017-03-10 20-32-28](https://cloud.githubusercontent.com/assets/8942495/23812045/b4b9a334-05d0-11e7-87c7-6923a4739cdf.png)

**Comment by 50Wliu** [comment]
> Electron: 1.4.15

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to bugs.archlinux.org/task/50357 for updates.

**Comment by libeclipse** [comment]
@50Wliu I wasn't aware it was an unofficial release, i installed it directly from pacman. How do I get onto the official one?

**Comment by 50Wliu** [comment]
You can download it from https://atom.io.

**Comment by Ben3eeE** [comment]
The version in the [AUR](https://aur.archlinux.org/packages/atom-editor-bin/) did not include mismatched versions of built in components last time I checked but it is not official.
