### ISSUE TITLE
losting a menu option for tools!

### ISSUE THREAD

**Issue by ppKrauss** [atom/markdown-preview#494]
I was using something as *menu/tools/markdown*... and not is there.

`alt+v` , `alt+...`  no menu.  Where is it or how to get back the "tools menu"?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by ppKrauss** [comment]
See https://stackoverflow.com/q/45661831/287948
