### ISSUE TITLE
Markdown preview- Bug

### ISSUE THREAD

**Issue by Adrian-Samuel** [atom/markdown-preview#498]
Markdown Preview seems to be buggy and affects things off the preview screen i'm working on.
Here is a gif that I made for example.

![markdown preview](https://user-images.githubusercontent.com/31516988/30251991-941d1fc0-9662-11e7-82aa-cad90b077a54.gif)

**Comment by rsese** [comment]
Thanks for reaching out!  In particular about the issue template besides all the basic details it asks for (Atom version, what operating system you're on, etc.), what would be super helpful is a detailed description describing of what the buggy behavior is in addition to exact steps to reproduce.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/markdown-preview/issues/276
