### ISSUE TITLE
Markdown preview does not update images when the image is changed externally.

### ISSUE THREAD

**Issue by JamesABaker** [atom/markdown-preview#562]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

A trivial issue where images are not updated until the text link is changed.

### Steps to Reproduce

1. Open markdown with an image file linked
2. Invoke markdown preview
3. Change the image file content externally without changing the link in markdown

**Expected behavior:** 

In the preview, the image refreshes to the new image when a file is changed.
Writing new markdown may trigger a refresh as the text updates.
Hiding and showing the preview might update the image.

**Actual behavior:** 

The image does not update until atom is restarted.

<img width="1852" alt="Screenshot 2019-05-22 at 14 15 24" src="https://user-images.githubusercontent.com/6866798/58177968-3ad10f80-7c9d-11e9-8354-a4afdccd19be.png">

**Additional info**
Possibly related to https://github.com/atom/atom/issues/18430
Possibly related to the cache being hard to clear https://github.com/atom/markdown-preview/issues/207.

**Reproduces how often:** 
100%

### Versions

OS: Mac OS 10.14.4 (18E226)
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.16
git 2.21.0

**Comment by rsese** [comment]
Thanks for the report!

> Possibly related to [atom/atom#18430](https://github.com/atom/atom/issues/18430)
> Possibly related to the cache being hard to clear #207.

Thanks for finding those :+1:  I think this sounds very much like #207 and as described below, we close issues as duplicates even if they're not exact duplicates.  If #207 is resolved and you're still seeing this behavior, we can always reopen.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
