### ISSUE TITLE
Nothing is rendered properly

### ISSUE THREAD

**Issue by Foadsf** [atom/markdown-preview#563]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The live preview does not render anything properly:

![rETTcnNYUS](https://user-images.githubusercontent.com/12762442/58284243-7c031580-7daa-11e9-8259-928cc723cf89.gif)

images, equations, ... nothing

### Steps to Reproduce

Just opened a MarkDown file

**Expected behavior:** [What you expect to happen]

The MarkDown file to be rendered properly

**Actual behavior:** [What actually happens]

The live preview doesn't work

**Reproduces how often:** [What percentage of the time does it reproduce?]

this happens all the time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3 x64
apm  2.1.7
npm  6.2.0
python 3.7.3
git 2.21.0.windows.1

Windows 10 1809

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
This package uses `marked` for rendering Markdown, which doesn't support many of the non-standard features such as LaTeX embedded in the document you show in your GIF.

You may be interested in [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus) or one of the other "enhanced" Markdown preview packages that add functionality beyond the basic features provided here, such as LaTeX rendering 😉.

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.

**Comment by Foadsf** [comment]
@Arcanemagus that's strange 🤔 because the files were rendered properly on my other Windows computer an I don't remember installing that plugin over there. Anyways even after installing the enhanced plugin, the images are not shown properly. I uninstalled Atom and now am using Visual Studio Code. Thanks for your support anyways.
