### ISSUE TITLE
Images not loading in preview

### ISSUE THREAD

**Issue by AnandKumar9** [atom/markdown-preview#569]
The image is not loading. This has started happening over last few weeks, and I can swear it wasn't happening over the year before that. Reinstalling the package or Atom itself does not help. It's replicable every single time for me.

```
Atom    : 1.39.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

markdown-preview: 0.160.2

OS: Mojave (macOS 10.14.5)
```

A sample image URL - 
```
![](assets/2. Adaptive Layouts - Interface Builder-828d4d40.png)
```

PS - I tried following the previous issues opened for same thing but they are very old now, and do not seem to have any specific solution other than updating Atom.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

It's unclear from your report if you're having issues with any images or just the example you shared.  I can't reproduce with a simple test example on 1.39.0 and macOS 10.14 (an image in `images/test.jpg`).

My guess is the issue is the spaces in the URL, see https://github.com/markedjs/marked/issues/1369.  If you encode the spaces with `%20` I think it should work.  If it doesn't, let me know and update your issue with the template details so we can take a look.
