### ISSUE TITLE
Interactive scroll bar ?

### ISSUE THREAD

**Issue by Lcornet** [atom/markdown-preview#573]
Dear atom team,

With markdown to pdf, is there any way to have an interactive scroll bar for codes?

thanks

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
