### ISSUE TITLE
Previewing Markdown Failed

### ISSUE THREAD

**Issue by jhongiv** [atom/markdown-preview#579]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**
always at first time preview. Sometimes second time preview is ok

### Versions
Atom 1.47.0
markdown-preview 0.160.2

### Additional Information

Previewing Markdown Failed
r.trim is not a function

**Comment by prxg22** [comment]
I've got the same error on Atom 1.48.0

**Comment by renemarcelo** [comment]
>  Sometimes second time preview is ok

I was able to trigger first render only by making a first action on the page (add newline, remove newline; renders correct.)

**Comment by angela-d** [comment]
This has persisted for the last 3 releases for me.
Current: 1.49.0
Debian 9,  4.9.0-12-amd64

![markdown-failed](https://user-images.githubusercontent.com/33108490/87716475-83d30580-c774-11ea-9805-ed5cf90b6baa.png)

Only stuff in the console log is for ruby aligner, don't see anything particularly related to this.

**Comment by ghowen** [comment]
It is still broken on Atom 1.49.0 on MacOS 10.15.6 when trying to display the default Jekyll start page.

![Bildschirmfoto 2020-07-22 um 17 24 43](https://user-images.githubusercontent.com/390784/88202660-1c6bf880-cc41-11ea-824d-8b8c4855ea36.png)

**Comment by beltex** [comment]
Just to update.

Same issue still on Atom `1.50.0` with macOS `10.15.6` and markdown-preview `0.160.2`. @renemarcelo's workaround still works though.

**Comment by j75** [comment]
Same problem on Atom 1.50.0 on Ubuntu Mate 18.04.

**Comment by gosukiwi** [comment]
Same here, `1.50.0` on Windows 10

**Comment by andrewpavlenko** [comment]
Can't reproduce this issue when running atom in dev mode. The only one place where `trim()` invokes in this extension is here https://github.com/atom/markdown-preview/blob/ae9f2e6e26015379eb138d991e3852b66ff16231/lib/renderer.js#L93
I think the issue may be caused by cherrio or dompurify, but here are no any errors in console output.

**Comment by gosukiwi** [comment]
Huh, same here. It works when running in dev mode, but in regular mode it crashes with the `r.trim` error.

Cheerio seems to be up to date, but DOMPurify is at version `1.0.10`. Maybe it needs to be upgraded? Still it would be better to track the issue first, I guess.

**Comment by j75** [comment]
Yes, I confirm that starting `atom --dev <my markdown file>` I may correctly display the markdown (my version is **1.51.0**).
My install says that all packages are updated - and I don't see anything about any **cherrio** or **DOMPurify** package (?), how could they be seen if there are installed?

**Comment by MaxLenormand** [comment]
Same error on `1.51.0` on Ubuntu 18.04

**Comment by nachoalonso** [comment]
As a workaround, running `apm install markdown-preview` solved the problem for me.

If you then run `apm uninstall markdown-preview` you get the error again.

This is strange because `apm view markdown-preview` shows I am on version 0.160.2 both when running the built-in and the community version of the package.

**Comment by angela-d** [comment]
I just tried @nachoalonso tip on Debian 10 and it seems to have solved it for me, too!

Very odd!  but thanks! :smile:

**Comment by alehaa** [comment]
However, this seems to trigger the deprecation cop:
> You have the core package "markdown-preview" installed as a community package.

**Comment by DaisySh** [comment]
Weird, but It works for openSUSE Tumbleweed (20201014) and Atom 1.52

**Comment by webuxr** [comment]
Same issue here "r.trim is not a function" with Atom 1.52.0x64 on MacOS Catalina 10.15.7.

Figured I'd subscribe to this thread since I'm now troubleshooting.

**Comment by webuxr** [comment]
Also, here's the README.md file I was trying to preview when the error appeared.
[README.txt](https://github.com/atom/markdown-preview/files/5475855/README.txt)

_Please note, since GitHub does not support uploading .md files, I changed to extension to .txt._

**Comment by seelphedvr** [comment]
I just had the same problem today, but it only shows when using the shortcut ctrl+shift+M. If I go to Packages>Preview HTML>Enable Preview it works. How odd.

**Comment by j75** [comment]
Where do you have that? I only have Packages -> Markdown preview -> Toggle

**Comment by racciari** [comment]
Same problem on MacOS 10.15.7, Atom 1.52.0 and markdown-preview 0.160.2

**Comment by wlwl2** [comment]
https://discuss.atom.io/t/version-1-4-7-and-markdown-preview/74943/16?u=wlwl2

There's a fix for it here.

**Comment by webuxr** [comment]
I tried this workaround. While it did work, as @wlwl2 mentioned, its only a temporary fix. I mean, selecting GitHub flavored (styled) markdown does get past the r.trim error (allowing the package to work), this certainly seems to be connected to the package’s theming functionlaity.

**Comment by j75** [comment]
There's a workaround though:

1. you display the markdown file,
1. then you type (on Linux at least) Ctrl + **M** to get the preview,
1. the window is splitted and on the right one (_Previewing Markdown Failed_) you have the infamous message `r.trim is not a function`,
1. now you close the window that shows the markdown file and by magic the preview window shows the markdown correctly rendered!

**Comment by seelphedvr** [comment]
Mine appears a little further down the list in Packages. I am running Atom in a win10 machine, same version 1.52.0
![image](https://user-images.githubusercontent.com/74009491/98720350-64499380-2388-11eb-86b2-d91b3b35f9f7.png)

**Comment by wlwl2** [comment]
Like I said before, I'm glad this bug happened. If you don't mind using a better package to view markdown here is a clean fix (**for now**):

Windows 10.0.19041 Build 19041, Atom Version 1.53.0

1. Install `markdown-preview-plus` (v 4.8.4).

2. It will automatically disable `markdown-preview`. Just make sure that `markdown-preview` from Core Packages is disabled.

3. Change Settings: 

`Packages that can affect preview rendering`:

Change from `fonts` to `*`.

I don't consider this optional even though it is, because I want the default atom markdown preview fonts restored.

`Preview position synchronization behavior`:

Check `Sync preview position when text in editor changes`.

Check `Sync preview position when text editor is scrolled`.

Check `Sync editor position when preview is scrolled`.

These 3 checkboxes are optional, but you should try them out first.

**Comment by wlwl2** [comment]
Some things maintainers of the official package could consider. I did think about how to resolve this for Core. Here are some of my thoughts:

1. **Maybe** you could remove the Core Package.

I'm guessing the reason that Core `markdown-preview` is still used, is for performance.

Otherwise you could add another extra special featured community packages list to install packages (**because this was once a Core Package**), and remove it from Core Packages.

But then why is `markdown-preview-plus` a preferred choice/so special? What if there are better options in the future with less downloads and stars from new package maintainers. Maybe there will be too many options.

2. Installer for Atom only one options page?

3. You could just fix the bug... but future users will miss out on a possibly better package (for many years like I did 😄). It might not be `markdown-preview-plus`.

4. You could just ignore all of this and maybe just fix the bug in the future. I'm a package maintainer myself. Time is scarce.
The images/GIFs not working right now on all packages in Core and Community on the official website seems to be down. I think that is a bigger priority for example, because we want good docs for our users (in that case).

**Comment by linucks** [comment]
Same issue here:
Mac OSX: 10.14.6
Atom: 1.53.0 x86

**Comment by nikahmadz** [comment]
Same here.
Windows 10
Atom: 1.53.0 x64

I need to press Ctrl+Shift+M (three times: error, close, normal)

**Comment by sjhuskey** [comment]
The message "Previewing Markdown Failed r.trim is not a function" appears the first time I toggle Markdown Preview on, but the second time the content is rendered as expected. The same happens each time I quit Atom and restart it.

Mac 10.15.7
Atom: 1.53.0 x64

**Comment by eddelbuettel** [comment]
Just for the record, still there with

Ubuntu 20,10
Atom 1.53

and package markdown-preview-plus works around it (thanks, @wlwl2) (but it is odd that it imposes a new CSS..., oh well).

**Comment by Neustradamus** [comment]
I have the same problem!

**Comment by sarahbhaskaran** [comment]
I had this problem and it went away when I put spaces between [the pound symbols] and [the header]
i.e. instead of ##Title I changed it to ## Title

**Comment by j75** [comment]
Same problem on Ubuntu 20.04 and atom 1.54.0 x64 ;-(

**Comment by chagelstein** [comment]
Right clicking on a file and choosing "Markdown Preview" worked
Microsoft Windows [Version 10.0.19042.746] Atom 1.54.0

**Comment by darkn3rd** [comment]
This reproduces a 100% for what seems like over a year now.
Clean install on Ubuntu or macOS, create markdown file (file.md) and preview.
If you make a small edit, like adding a space, it then suddenly works.

### OS Version
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

### Atom Version
```
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```

**Comment by eddelbuettel** [comment]
IIRC the smal edit is not needed.  Just requesting the render _twice_ works the second time.

**Comment by j75** [comment]
I confirm (on Ubuntu 20.04 with atom **1.54.0**) - not _twice_ but _three_ times! The second time the rendering window closes, and the third time it renders markdown correctly.

**Comment by madler** [comment]
Still there. Atom 1.54.0, macOS 11.1.

I downloaded this specifically to edit and preview markdown. Entirely useless.

**Comment by borisbLL** [comment]
I noticed recently this behavior and I didn't have any issue at all before, since my last Desktop setup:
I put it out there, maybe it helps somebody else as well with this nasty issue (at least who is running Ubuntu/snaps):

- how I reproduced the markdown-preview error:
since installed Atom 1.54.0 x64 on a fresh Ubuntu 20.04 never had any issue and the markdown-preview was working just perfectly.
by error I run a second instance of atom (while I had the first instance of the app running in another virtual desktop); 
the issue with the markdown-preview started manifesting afterwards. (I knew and hated this as I had suffered from it on a previous Ubuntu 16/18 setup)

I came to this issue #579 in desperation and ran @nachoalonso workaround with the community package. 
https://github.com/atom/markdown-preview/issues/579#issuecomment-705827134
but my atom App icon disappeared from the OS bar (that's where I thought about Ubuntu snaps! like "ups I did it again"-style by Britney Spears)..

I am not sure yet why or how and you probably know better, but I believe it may be linked to the way Ubuntu handles snaps and apps confinement - specifically this atom snap.

in `/var/lib/snapd/desktop/applications/atom_atom.desktop` change 
`Icon=/snap/atom/263/usr/share/pixmaps/atom.png` to `Icon=/snap/atom/current/usr/share/pixmaps/atom.png`

**current** is a symlink in `/snap/atom/` that points to the latest snap running on your system for that app. 
This did the trick and popped back up the Atom icon.

- I disabled the package markdown-preview from inside atom and closed the app.  
- `apm uninstall markdown-preview` to remove the package  
- restarted Atom and enabled the core markdown-preview again from within the App.  

CTRL+SHIFT+M works again and beautifully (no `r.trim` error)   :tada: :sunglasses: 

ah one last note, you may want to consider refreshing your snaps and/or deleting the old stales ones if they are left laying around. 

refs and credits :pray:  go to:
@nachoalonso  (obviously for his first fix)  
@majcherek2048 (for his reply on an old post https://github.com/atom/atom/issues/9667 that sparked the idea that led me to this fix the icon issue
@daviwil  for his post and explanation on https://github.com/atom/atom/blob/master/packages/dalek/README.md

**Comment by jhongiv** [comment]
Thank you all for the answers ... I absolutely forgot this issue and now I find so many answers ... I have tried @nachoalonso solution, and it worked when restarting atom ... thank you very much ...

**Comment by eddelbuettel** [comment]
I don't use the snap (but a standard `.deb`) and still have the problem so closing this seems premature.

**Comment by Neustradamus** [comment]
The problem is solved?
If not, this issue must not be closed.

**Comment by eddelbuettel** [comment]
It is not.  As I wrote. I can write it again.

- Ubuntu 20.10, fairly vanilla, number of packages installed
- atom 1.54.0, from https://packagecloud.io/AtomEditor/atom/any via `apt`, regular updates
- not (fully) functional for markdown preview which, as @madler wrote above, is the main reason to install it for many of us

#### Demo

```sh
$ echo "## Headline" > testfile.md
$ atom testfile.md 
$ # now pressing Control-M in the editor on `testfile.md`
```

#### Result 

![image](https://user-images.githubusercontent.com/673121/106903519-b10ae500-66bf-11eb-99a7-9b7b7dec41a6.png)


I am not sure how much clearer we can make this.

**Comment by j75** [comment]
> As a workaround, running `apm install markdown-preview` solved the problem for me.

Yes, that works for me too (on Ubuntu 20.04 + Atom 1.54.0 x64), but  when installing I noticed  the following message :
```
The markdown-preview package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall markdown-preview` to uninstall it and then the version bundled
with Atom will be used.
Installing markdown-preview to ~/.atom/packages
```
So I would rather say that there's something wrong with the bundled package...

**Comment by eddelbuettel** [comment]
I am apparently using the bundled version, which is the one that fails:

```sh
$ dpkg -l | grep markdown-preview
$ apm uninstall markdown-preview
Uninstalling markdown-preview ✗
Failed to delete markdown-preview: No package.json found at /home/edd/.atom/packages/markdown-preview/package.json
$ 
```

**Comment by eddelbuettel** [comment]
But you are right: doing _the opposite of what the message says_ works:

```sh
$ apm uninstall markdown-preview
Uninstalling markdown-preview ✗
Failed to delete markdown-preview: No package.json found at /home/edd/.atom/packages/markdown-preview/package.json
$ apm install markdown-preview
The markdown-preview package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall markdown-preview` to uninstall it and then the version bundled
with Atom will be used.
Installing markdown-preview to /home/edd/.atom/packages ✓
$
```

So if we 

- just ignore to line noise from that message
- get everybody to `apm install markdown-preview` to _ignore_ the (apparently bad) built-in version

then things appear to work.  At last.  Thanks for the help!

**Comment by j75** [comment]
For me, this is not solving a bug but just a way of avoiding it!

**Comment by eddelbuettel** [comment]
Completely agree.  It requires an additional installation of the _same_ package rather than, as I had done for a while, of an alternate package (namely `markdown-preview-plus`).  I like the default look better, so this beats hitting `C-m` three times...

You'd think that someone with the resource of GitHub (and, hence, Microsoft) could fix this eventually...

**Comment by rugk** [comment]
…cough well, guess ~~GitHub~~ MS has other ~~priorities~~ editors/IDEs now. Apparently…

**Comment by Guymer** [comment]
I still experience this on 1.54.0 on macOS Big Sur 11.2.1 (why did the ticket get closed?) I too can avoid it by typing a single character and forcing the preview to re-render, but as @j75 said: that is simply avoiding the bug, not fixing it.

**Comment by rickalex21** [comment]
This is still a problem, I don't want to use plugins but I think I'm going to have to. This is my first time using atom.

**Comment by angela-d** [comment]
> I don't want to use plugins

One of the best parts about Atom is the amount of customizations you can get with plugins!  The themes and linters are excellent.

**Comment by rickalex21** [comment]
> One of the best parts about Atom is the amount of customizations you can get with plugins! The themes and linters are excellent.

Really ? I did not look much but the market in atom looked very limited compared to visual studio code. They don't even have a vim plugin like visual studio code does. I mostly use vim, occasionally I need to use vscode for something like markdown. Vscode is very active and constantly improving.

**Comment by angela-d** [comment]
VS Code also has Microsoft's telemetry strings attached, so it depends on what's important to you.

If you prefer the plugin environment of VS Code, this fork has the telemetry stuff removed: https://vscodium.com/

For my personal use case, everything I've needed has been available in Atom, so far; and I prefer not to be monitored by a code editor.

**Comment by gosukiwi** [comment]
> > One of the best parts about Atom is the amount of customizations you can get with plugins! The themes and linters are excellent.
> 
> Really ? I did not look much but the market in atom looked very limited compared to visual studio code. They don't even have a vim plugin like visual studio code does. I mostly use vim, occasionally I need to use vscode for something like markdown. Vscode is very active and constantly improving.

There's `vim-mode-plus` for Atom.

**Comment by rickalex21** [comment]
@angela-d Very good point. Thanks.

@gosukiwi  I will have to check that out. Thanks.

**Comment by BraperBlueSage** [comment]
Confirmed : This bug has not been addressed. Atom 1.54.0 x64 :  Macos 11.2.2

~/.atom/config.cson 

```
  "markdown-preview":
    useGitHubStyle: true
```
Installing markdown-preview-plus > Markdown-preview-plus has disabled markdown-preview package.

This will allow Atom to correctly render markdown. But as wlwl2 mentioned, you must change the default configuration for fonts to be * - otherwise you will get a serifed font

**Comment by ScottA38** [comment]
I'm not sure if this was already covered in other comments but I managed to circumvent this issue by toggling 

> break on single newline

**Comment by anyboo** [comment]
OS Version
ProductName:	Windows
ProductVersion: 10.0.17763.194
BuildVersion:	17763

Atom Version
Atom    : 1.55.0


![image](https://user-images.githubusercontent.com/2034799/114510128-df311600-9c68-11eb-94c0-c3df6f30e0af.png)

**Comment by anyboo** [comment]
I found that reinstall the markdown-preview will be ok. May be the bundle version was not work.

 `apm uninstall markdown-preview` 
then
 `apm install markdown-preview`

**Comment by dbubenheim** [comment]
I solved the issue by disabling and enabling the plugin again in the settings dialog

![atom-markdown-plugin](https://user-images.githubusercontent.com/7910396/116827999-4f61f600-ab9c-11eb-8b2d-c3dd0635e69f.png)

**Comment by Fuse56** [comment]
This bug is still occurring in markdown-preview as of July 13th 2021.  Why was this thread closed?
![markdown_rtrim_bug](https://user-images.githubusercontent.com/22082454/125535439-a6989b4e-e7b6-41db-8841-f83ec86b0c5c.JPG)


The only packages I'm using are:

1. language-markdown
2. markdown-writer
3. markdown-preview
on Windows 10
Atom 1.48.0 x64

**Comment by Neustradamus** [comment]
I think that WE must to open a new ticket!

**Comment by cvarta** [comment]
I was suffering from the same r.trim is not a function error. I trashed my installation of atom including settings and setup a new installation. So far I haven't seen this error come up again.

**Comment by Fuse56** [comment]
Thanks, Chris. That didn't work for me initially, but I may try again.

**Comment by wlwl2** [comment]
@Fuse56 I've recently fixed this issue on Windows 10. Changing my user folder to have no spaces (e.g. `C:\Users\william`), and then reformatting my computer and reinstalling atom solved this issue.

**Comment by frederik-b** [comment]
still an unsolved issue
toggling it open twice solves it
inital opening of the preview still has this bug
